apiVersion: v1
kind: Service
metadata:
  name: fortio-server
  labels:
    app: fortio-server
    service: fortio-server
spec:
  type: NodePort
  ports:
  - name: proxy
    nodePort: 30990
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: http-echo
    nodePort: 30980
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: fortio-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fortio-server
  labels:
    account: fortio-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio-server
  labels:
    app: fortio-server
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio-server
      version: v1
  template:
    metadata:
      labels:
        app: fortio-server
        version: v1
        sys: benchmark
      annotations:
        flomesh.io/inject: "true"
    spec:
      serviceAccountName: fortio-server
      containers:
      - name: fortio
        image: fortio/fortio:1.17.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-echo
          containerPort: 8080
          protocol: TCP
        securityContext:
          runAsUser: 1000
